main: sotumney.BlockBedrockBoats
name: BlockBedrockBoats
version: "1.5"
api-version: "1.21.1"
author: Sotumney
description: An extremely barebones plugin to block Bedrock players joining a Java server.
folia-supported: true
commands:
  togglebedrockblock:
    description: Toggles whether players can connect using Geyser.
    usage: "Just use the command lol"
permissions:
  blockbedrockboats.allowtoggle:
    description: Gives permission whether a user can use commands from this plugin.
    default: op
